[2025-05-31T08:57:02.862+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-31T08:57:02.871+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: medallion_sales_etl.ensure_datalake_bucket_exists manual__2025-05-31T08:57:01.890670+00:00 [queued]>
[2025-05-31T08:57:02.875+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: medallion_sales_etl.ensure_datalake_bucket_exists manual__2025-05-31T08:57:01.890670+00:00 [queued]>
[2025-05-31T08:57:02.876+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-31T08:57:02.881+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): ensure_datalake_bucket_exists> on 2025-05-31 08:57:01.890670+00:00
[2025-05-31T08:57:02.884+0000] {standard_task_runner.py:72} INFO - Started process 192 to run task
[2025-05-31T08:57:02.886+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'medallion_sales_etl', 'ensure_datalake_bucket_exists', 'manual__2025-05-31T08:57:01.890670+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/medallion_sales_etl_dag.py', '--cfg-path', '/tmp/tmp69y2ubyx']
[2025-05-31T08:57:02.888+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask ensure_datalake_bucket_exists
[2025-05-31T08:57:02.918+0000] {task_command.py:467} INFO - Running <TaskInstance: medallion_sales_etl.ensure_datalake_bucket_exists manual__2025-05-31T08:57:01.890670+00:00 [running]> on host 0054c26eb672
[2025-05-31T08:57:02.971+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='medallion_sales_etl' AIRFLOW_CTX_TASK_ID='ensure_datalake_bucket_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-05-31T08:57:01.890670+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-31T08:57:01.890670+00:00'
[2025-05-31T08:57:02.972+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-31T08:57:02.990+0000] {logging_mixin.py:190} INFO - Error: MINIO_ACCESS_KEY or MINIO_SECRET_KEY environment variables not set.
[2025-05-31T08:57:02.991+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/include/custom_utils/minio_utils.py", line 21, in ensure_bucket_exists
    raise ValueError("MinIO access/secret key not found in environment variables.")
ValueError: MinIO access/secret key not found in environment variables.
[2025-05-31T08:57:02.998+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=medallion_sales_etl, task_id=ensure_datalake_bucket_exists, run_id=manual__2025-05-31T08:57:01.890670+00:00, execution_date=20250531T085701, start_date=20250531T085702, end_date=20250531T085702
[2025-05-31T08:57:03.004+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-31T08:57:03.005+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 17 for task ensure_datalake_bucket_exists (MinIO access/secret key not found in environment variables.; 192)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/include/custom_utils/minio_utils.py", line 21, in ensure_bucket_exists
    raise ValueError("MinIO access/secret key not found in environment variables.")
ValueError: MinIO access/secret key not found in environment variables.
[2025-05-31T08:57:03.026+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-31T08:57:03.039+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-31T08:57:03.041+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
